(async()=>{
const Settings=require('./config.cjs');
const Fields=require('./fields.cjs');
const PG=await require('./postgres.cjs')();
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const M=require('./model.cjs'), Sync=require('./sync.cjs'),T=require('./tournament.cjs');
const ROOT=__dirname, DATA=Settings.dataDir, FILE=path.join(DATA,'macarena.json');
fs.mkdirSync(DATA,{recursive:true});let state=PG.state;M.validate(state);Sync.migrate(state);
const Storage=require('./storage.cjs'),Vault=require('./password-vault.cjs')(DATA);
let committed=structuredClone(state);
async function persist(){await PG.save(state,committed);committed=structuredClone(state);}

const SESSION_FILE=path.join(DATA,'sessions.json'),SESSION_MS=7*24*3600000;
const sessions=new Map(PG.sessions),attempts=new Map(),streams=new Set();
const tokenKey=token=>crypto.createHash('sha256').update(token||'').digest('hex');
async function saveSessions(){for(const [key,value] of sessions)if(value.expires<Date.now())sessions.delete(key);await PG.saveSessions([...sessions]);}
let scoreNotice=null;function publish(){for(const client of streams)client.res.write('event: changed\ndata: {}\n\n');}function notify(action){if(action==='score'){if(!scoreNotice)scoreNotice=setTimeout(()=>{scoreNotice=null;publish();},1000);return;}if(scoreNotice){clearTimeout(scoreNotice);scoreNotice=null;}publish();}
const heartbeat=setInterval(()=>{for(const client of streams){const active=sessions.get(client.key),u=active&&state.players.find(p=>p.id===active.id&&p.active);if(!active||active.expires<Date.now()||!u){client.res.end();streams.delete(client);}else client.res.write(': keepalive\n\n');}},20000);heartbeat.unref();
async function record(user,action,details){state.audit.push({at:new Date().toISOString(),user:user.id,action,...details,...require('./audit.cjs').entry(committed,state,action,details)});try{await persist();}catch(e){state=structuredClone(committed);throw e;}notify(action);}
let configState=null,configHash=null;
function configVersion(){if(configState===committed)return configHash;configState=committed;return configHash=crypto.createHash('sha256').update(JSON.stringify([state.tournamentGeneration,state.players,state.groups,state.members,state.assignments,state.course,state.tournament,state.editing,state.rainFinalization])).digest('hex');}
let viewState=null;const views=new Map();
function publicState(user){if(viewState!==committed){views.clear();viewState=committed;}let value=views.get(user.id);if(!value){value=buildPublicState(user);views.set(user.id,value);}return {...value,serverTime:Date.now(),offlineUntil:Date.now()+SESSION_MS};}
function buildPublicState(user){const {receipts,...shared}=committed;return {...shared,configVersion:configVersion(),tournament:{title:committed.tournament?.title||T.defaults.title,subtitle:committed.tournament?.subtitle||T.defaults.subtitle,date:committed.tournament?.date||'',logoVersion:crypto.createHash('sha256').update(committed.tournament?.logo||'default').digest('hex').slice(0,12)},serverTime:Date.now(),offlineUntil:Date.now()+SESSION_MS,players:committed.players.map(({passwordHash,passwordEncrypted,...p})=>p),audit:[],me:user.id,permissions:Object.fromEntries(committed.groups.map(g=>[g.id,M.canEdit(committed,user,g.id)]))};}
function error(message,status=400){const e=Error(message);e.status=status;throw e;}
async function body(req){let text='';for await(const chunk of req){text+=chunk;if(text.length>2000000)error('Solicitud demasiado grande',413);}try{return JSON.parse(text||'{}')}catch{error('Solicitud inválida')}}
function admin(user){if(!user.admin)error('Solo administradores',403);}
let requestTail=Promise.resolve();
const server=http.createServer(async(req,res)=>{const previous=requestTail;let release;requestTail=new Promise(r=>release=r);await previous;try{const recovered=await PG.recover();if(recovered){state=recovered.state;committed=structuredClone(state);sessions.clear();for(const [key,value] of recovered.sessions)sessions.set(key,value);notify('recovery');}
 const url=new URL(req.url,'http://localhost');
 res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Cache-Control','no-store');
 const json=(value,status=200)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(value));};
 if(req.method!=='GET'&&req.headers.origin&&req.headers.origin!==(process.env.PUBLIC_ORIGIN||`http://${req.headers.host}`))error('Origen no autorizado',403);
 if(url.pathname==='/health'){try{await PG.health();return json({ok:true});}catch{return json({ok:false},503);}}
 if(url.pathname==='/api/login'&&req.method==='POST'){const b=await body(req);Fields.id(b.id);Fields.password(b.password);const key=req.socket.remoteAddress;const a=attempts.get(key)||{count:0,until:Date.now()+60000};if(a.until<Date.now()){a.count=0;a.until=Date.now()+60000;}if(a.count>=20)error('Espere un minuto antes de intentar nuevamente',429);const u=state.players.find(p=>p.id===b.id&&p.active);if(!u||!M.passwordMatches(String(b.password||''),u.passwordHash)){a.count++;attempts.set(key,a);error('Cédula o clave incorrecta',401);}if(!u.passwordEncrypted){u.passwordEncrypted=Vault.encrypt(String(b.password));try{await persist();}catch(e){state=structuredClone(committed);throw e;}}attempts.delete(key);const token=crypto.randomBytes(32).toString('hex');sessions.set(tokenKey(token),{id:u.id,expires:Date.now()+SESSION_MS});await saveSessions();res.setHeader('Set-Cookie',`macarena_session=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=604800${process.env.PUBLIC_ORIGIN?.startsWith('https:')?'; Secure':''}`);return json({ok:true});}
 if(url.pathname.startsWith('/api/')){
 const token=req.headers.cookie?.match(/(?:^|; )macarena_session=([^;]+)/)?.[1],session=sessions.get(tokenKey(token)),user=session&&session.expires>Date.now()&&state.players.find(p=>p.id===session.id&&p.active);if(!user)error('Inicie sesión',401);
 if(url.pathname==='/api/logout'){sessions.delete(tokenKey(token));await saveSessions();res.setHeader('Set-Cookie','macarena_session=; Max-Age=0; Path=/');return json({ok:true});}
 if(url.pathname==='/api/events'&&req.method==='GET'){res.writeHead(200,{'Content-Type':'text/event-stream','Connection':'keep-alive','X-Accel-Buffering':'no'});res.write('event: changed\ndata: {}\n\n');const client={res,key:tokenKey(token)};streams.add(client);req.on('close',()=>streams.delete(client));return;}
 if(url.pathname==='/api/history'&&req.method==='GET'){admin(user);const from=url.searchParams.get('from')||'',to=url.searchParams.get('to')||'',functionality=url.searchParams.get('functionality')||'';for(const date of [from,to])if(date&&(!/^\d{4}-\d{2}-\d{2}$/.test(date)||Number.isNaN(Date.parse(date))||new Date(date).toISOString().slice(0,10)!==date))error('Fecha de historial inválida');if(from&&to&&from>to)error('La fecha Desde no puede ser posterior a Hasta');const limit=50;const rows=committed.audit.map(a=>{const {at,user,action,area,functionality,description}=require('./audit.cjs').present(a,committed);return {at,user,action,area,functionality,description};}).filter(a=>{const day=new Date(a.at).toLocaleDateString('en-CA',{timeZone:'America/Bogota'});return (!from||day>=from)&&(!to||day<=to)&&(!functionality||a.functionality===functionality);}).reverse();const pages=Math.max(1,Math.ceil(rows.length/limit)),page=Math.min(pages,Math.max(1,Number.parseInt(url.searchParams.get('page'),10)||1));return json({audit:rows.slice((page-1)*limit,page*limit),page,pages,total:rows.length,generation:committed.tournamentGeneration||0});}
 if(url.pathname==='/api/player-password'&&req.method==='GET'){admin(user);const p=state.players.find(p=>p.id===url.searchParams.get('id'));if(!p)error('Jugador no encontrado',404);return json({password:Vault.decrypt(p.passwordEncrypted)});}
 if(url.pathname==='/api/master-delete-check'&&req.method==='GET')return json(require('./master-delete.cjs').inspect(state,user,url.searchParams.get('type'),url.searchParams.get('id')));
 if(url.pathname==='/api/reset-tournament-check'&&req.method==='GET'){admin(user);return json({version:require('./reset-tournament.cjs').version(state)});}
 if(url.pathname==='/api/state'&&req.method==='GET'){const full=publicState(user);return json(req.headers['x-macarena-state']?(require('./state-wire.cjs')(full,req.headers['x-macarena-state'])||full):full);}
 if((url.pathname==='/api/card.pdf'||url.pathname==='/api/card-image')&&req.method==='GET'){const id=url.searchParams.get('group');if(!state.cards[id])error('Tarjeta no encontrada',404);if(!state.cards[id].finalized||state.cards[id].finalized.pending)error('Finalice la tarjeta antes de descargarla',403);const format=url.pathname==='/api/card-image'?'PNG':'PDF',output=require('./pdf.cjs')(state,id,format==='PNG'?'image':'pdf');await record(user,'download',{groupId:id,format});if(format==='PNG')return json(output);res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition',`attachment; filename="Macarena-${id}.pdf"`);return res.end(output);}
 if(req.method!=='POST')error('Ruta no disponible',404);const b=await body(req);
 if(['/api/master','/api/roster','/api/editing','/api/rain-finalization','/api/reopen','/api/master-delete'].includes(url.pathname)&&b.baseConfigVersion&&b.baseConfigVersion!==configVersion())error('La configuración cambió en otro dispositivo. Revise los datos antes de guardar.',409);
 if(url.pathname==='/api/confirm'){if(!Array.isArray(b.operations)||b.operations.length>5)error('Consulta inválida');const confirmed=b.operations.filter(op=>require('./confirmation.cjs').confirmed(committed,user,op)).map(op=>op.id);return json({confirmed,state:publicState(user)});}
 if(url.pathname==='/api/sync'){const result=Sync.apply(state,user,b);if(!result.duplicate)await record(user,b.type,{groupId:b.groupId,hole:b.hole===undefined?undefined:b.hole+1,score:b.score,operationId:b.id,recordedAt:b.createdAt,administrative:b.type==='finalize'?state.cards[b.groupId].finalized.administrative:undefined});}
 else if(url.pathname==='/api/clear-history'){admin(user);if(b.confirm!==true)error('Confirme que desea borrar todo el historial');state.audit=[];await record(user,'clear-history',{});}
 else if(url.pathname==='/api/rain-finalization'){admin(user);if(typeof b.enabled!=='boolean')error('Valor inválido');state.rainFinalization=b.enabled;await record(user,'rain-finalization',{enabled:b.enabled});}
 else if(url.pathname==='/api/editing'){admin(user);if(typeof b.enabled!=='boolean')error('Valor inválido');state.editing=b.enabled;await record(user,'editing',{enabled:b.enabled});}
 else if(url.pathname==='/api/score'){const card=state.cards[b.groupId];if(!card||!M.canEdit(state,user,b.groupId))error('No tiene permiso para editar esta tarjeta',403);if(card.revision!==b.revision)error('La tarjeta cambió. Se actualizará antes de volver a guardar.',409);if(!Number.isInteger(b.hole)||b.hole<0||b.hole>17||b.score!==null&&(!Number.isInteger(b.score)||b.score<1||b.score>19))error('Registre entre 1 y 19 golpes');require('./public/scoring.js').validateSequence(card.scores,M.startOf(state,b.groupId),b.hole,b.score);const previous=card.scores[b.hole];card.scores[b.hole]=b.score;card.holeVersions[b.hole]++;card.revision++;await record(user,'score',{groupId:b.groupId,hole:b.hole+1,previous,score:b.score});}
 else if(url.pathname==='/api/finalize'){const card=state.cards[b.groupId];if(!card||!M.canEdit(state,user,b.groupId))error('No tiene permiso para finalizar',403);if(card.revision!==b.revision)error('La tarjeta cambió. Revise los golpes antes de firmar.',409);if(!user.admin&&!state.rainFinalization&&card.scores.some(x=>x===null))error('Complete los 18 hoyos');if(!Array.isArray(b.signatures)||b.signatures.length!==2||b.signatures.some(s=>!/^data:image\/jpeg;base64,[A-Za-z0-9+/=]+$/.test(s)||s.length<1500||s.length>500000))error('Se requieren las dos firmas');const captain=state.members.find(m=>m.groupId===b.groupId&&m.captain&&state.players.some(p=>p.id===m.playerId&&p.active));const writer=state.assignments.find(a=>a.groupId===b.groupId);if(!captain||!writer)error('Configure capitán y anotador');card.finalized={at:new Date().toISOString(),by:user.id,captain:captain.playerId,writer:writer.playerId,signatures:b.signatures,administrative:!!user.admin&&card.scores.some(v=>v===null),rain:!user.admin&&card.scores.some(v=>v===null),scores:[...card.scores]};card.revision++;await record(user,'finalize',{groupId:b.groupId,administrative:card.finalized.administrative});}
 else if(url.pathname==='/api/reset-tournament'){admin(user);state=require('./reset-tournament.cjs').reset(state,b);await record(user,'reset-tournament',{});for(const [key,session] of sessions)if(!state.players.some(p=>p.id===session.id))sessions.delete(key);await saveSessions();}
 else if(url.pathname==='/api/reset-card'){admin(user);if(b.confirm!==true)error('Confirme el reinicio de esta tarjeta');const card=state.cards[b.groupId];if(!card)error('Tarjeta no encontrada',404);if(card.revision!==b.revision)error('La tarjeta cambió. Revise y confirme nuevamente.',409);const generation=card.generation+1;state.cards[b.groupId]={scores:Array(18).fill(null),holeVersions:Array(18).fill(0),revision:card.revision+1,generation,resetGeneration:generation,finalized:null};await record(user,'reset-card',{groupId:b.groupId});}
 else if(url.pathname==='/api/reset-cards'){admin(user);if(b.confirm!==true)error('Confirme el reinicio de todas las tarjetas');if(!b.revisions||Object.keys(b.revisions).length!==Object.keys(state.cards).length||Object.entries(state.cards).some(([id,c])=>b.revisions[id]!==c.revision))error('Las tarjetas cambiaron. Revise y confirme nuevamente.',409);const count=Object.keys(state.cards).length;for(const [id,c] of Object.entries(state.cards)){const generation=c.generation+1;state.cards[id]={scores:Array(18).fill(null),holeVersions:Array(18).fill(0),revision:c.revision+1,generation,resetGeneration:generation,finalized:null};}await record(user,'reset-cards',{count});}
 else if(url.pathname==='/api/reopen'){admin(user);const card=state.cards[b.groupId];if(!card?.finalized)error('La tarjeta no está finalizada');const previous=card.finalized;card.finalized=null;card.generation++;card.revision++;await record(user,'reopen',{groupId:b.groupId,previous});}
 else if(url.pathname==='/api/roster'){admin(user);const next=structuredClone(state);require('./roster.cjs').apply(next,b);M.validate(next);state=next;await record(user,'roster',{groupId:b.groupId,rosterAction:b.action,closed:!!state.groups.find(g=>g.id===b.groupId).rosterClosed});}
 else if(url.pathname==='/api/master-delete'){admin(user);if(b.confirm!==true)error('Confirme que desea eliminar el registro');const next=structuredClone(state);require('./master-delete.cjs').remove(next,user,b.type,b.id,b.version);M.validate(next);state=next;await record(user,'master',{type:b.type,id:b.id,...(b.type==='members'?{playerId:b.id}:b.type==='assignments'?{groupId:b.id}:{})});}
 else if(url.pathname==='/api/master'){
 admin(user);if(b.remove)error('Use Eliminar y confirme la eliminación del registro');const next=structuredClone(state);const r=b.record;Fields.master(b.type,r);
 if(b.type==='tournament'){next.tournament=T.validate({...T.defaults,...state.tournament,...r});}
 else if(b.type==='course'){
 const name=String(r.name||'').trim(),pars=r.pars;
 if(!name)error('El nombre de la cancha es obligatorio');
 const parsChanged=JSON.stringify(pars)!==JSON.stringify(state.course.pars);
 if(parsChanged&&Object.values(state.cards).some(c=>c.scores.some(x=>x!==null)))error('El par no puede cambiar después de registrar golpes');
 next.course={name,pars:parsChanged?pars:state.course.pars};
}
 else if(b.type==='players'){const old=next.players.find(p=>p.id===r.id);const player={id:String(r.id||'').trim(),name:String(r.name||'').trim(),surname:String(r.surname||'').trim(),category:r.category,active:r.active,admin:r.admin,passwordEncrypted:r.password?Vault.encrypt(String(r.password)):old?.passwordEncrypted,passwordHash:r.password?M.passwordHash(String(r.password)):old?.passwordHash};if(!old&&!r.password)error('La clave es obligatoria');if(old)next.players[next.players.indexOf(old)]=player;else next.players.push(player);}
 else if(b.type==='groups'){const old=next.groups.find(g=>g.id===r.id);const group={id:r.id,name:r.name,active:r.active,rosterClosed:!!old?.rosterClosed};if(old)next.groups[next.groups.indexOf(old)]=group;else {next.groups.push(group);next.cards[r.id]={scores:Array(18).fill(null),revision:0,finalized:null,generation:state.tournamentGeneration||0,resetGeneration:state.tournamentGeneration||0};}}
 else if(b.type==='members'){error('Use el formulario de integrantes por grupo');if(state.groups.some(g=>g.rosterClosed&&(g.id===r.groupId||state.members.some(m=>m.playerId===r.playerId&&m.groupId===g.id))))error('El grupo está cerrado. Ábralo antes de modificar integrantes.');const old=next.members.find(m=>m.playerId===r.playerId);const touched=[old?.groupId,r.groupId];if(touched.some(g=>next.cards[g]?.scores.some(x=>x!==null)))error('No cambie integrantes o salida después de registrar golpes');if(b.remove)next.members=next.members.filter(m=>m.playerId!==r.playerId);else if(old)next.members[next.members.indexOf(old)]={groupId:r.groupId,playerId:r.playerId,start:Number(r.start)};else next.members.push({groupId:r.groupId,playerId:r.playerId,start:Number(r.start)});}
 else if(b.type==='assignments'){const existing=next.assignments.find(a=>a.groupId===r.groupId);if(!b.remove){if(b.editId){if(b.editId!==r.groupId||!existing)error('La asignación cambió. Abra el registro de nuevo.',409);}else if(existing){const group=next.groups.find(g=>g.id===r.groupId);error(`Ya existe una asignación para ${group?.name||r.groupId}. Use Editar para cambiar el anotador.`,409);}}if(next.cards[r.groupId]?.finalized)error('Reabra la tarjeta antes de cambiar su anotador');next.assignments=next.assignments.filter(a=>a.groupId!==r.groupId);if(!b.remove)next.assignments.push({groupId:r.groupId,playerId:r.playerId});}
 else error('Maestro no válido');M.validate(next);if(!next.players.find(p=>p.id===user.id)?.admin||!next.players.find(p=>p.id===user.id)?.active)error('No puede desactivar su propio acceso de administrador');state=next;Sync.migrate(state);await record(user,'master',{type:b.type,id:r.id||r.groupId||r.playerId,groupId:r.groupId,playerId:r.playerId});
 }else error('Ruta no disponible',404);
 return json(publicState(user));
 }
 if(url.pathname==='/tournament-logo.jpg'){res.setHeader('Content-Type','image/jpeg');return res.end(T.logo(state).bytes);}
 const files={'/':'index.html','/app.js':'app.js','/scoring.js':'scoring.js','/offline.js':'offline.js','/styles.css':'styles.css','/sw.js':'sw.js','/manifest.webmanifest':'manifest.webmanifest','/icon.svg':'icon.svg','/tournament-logo.jpg':'tournament-logo.jpg'};if(!files[url.pathname])error('No encontrado',404);res.setHeader('Content-Type',url.pathname.endsWith('.js')?'text/javascript; charset=utf-8':url.pathname.endsWith('.css')?'text/css; charset=utf-8':url.pathname.endsWith('.webmanifest')?'application/manifest+json':url.pathname.endsWith('.svg')?'image/svg+xml':url.pathname.endsWith('.jpg')?'image/jpeg':'text/html; charset=utf-8');res.end(fs.readFileSync(path.join(ROOT,'public',files[url.pathname])));
 }catch(e){res.writeHead(e.status||400,{'Content-Type':'application/json; charset=utf-8'});if(e.status===503)console.error('Guardado no confirmado:',e.cause?.code||'storage');res.end(JSON.stringify({error:e.code?'No pudimos completar la operación. Intente nuevamente.':e.message,...(e.status===401?{tournamentGeneration:state.tournamentGeneration||0}:{})}));}finally{release();}});
server.listen(Settings.port,Settings.host,()=>console.log(`Tarjeta Macarena: http://127.0.0.1:${process.env.PORT||8769}`));


})().catch(e=>{console.error(e.message);process.exit(1)});
